config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources 'duels' do
    resources 'comments'
  end
  resources 'users', only: [:index, :show]
  root "duels#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :duel
  default_scope { order('created_at desc')}
  validates_presence_of :body


end

app/models/duel.rb
class Duel < ActiveRecord::Base

  has_many :comments
  belongs_to :user
  validates_presence_of :name, :character_two_name, :character_two_body, :character_one_name, :character_one_body

  default_scope { order(created_at: :desc) }

  has_attached_file :character_one_avatar, :styles => { :medium => "200x200>", :thumb => "100x100>" }, :default_url => "missing.png"
  has_attached_file :character_two_avatar, :styles => { :medium => "200x200>", :thumb => "100x100>" }, :default_url => "missing.png"

  validates_attachment_content_type :character_one_avatar, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :character_two_avatar, :content_type => /\Aimage\/.*\Z/

  #can have no argument for the native image size, or one argument determining the size.
  def character_one_image(*args)
    character_one_avatar.url(*args)
  end

  def character_two_image(*args)
    character_two_avatar.url(*args)
  end

  def total_votes
    character_two_votes + character_one_votes
  end

  def vote_percent_one
    character_one_votes.to_f / total_votes.to_f * 100
  end
  def vote_percent_two
    character_two_votes.to_f / total_votes.to_f * 100

  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name, :email
  has_many :duels
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:name, :admin]
    devise_parameter_sanitizer.for(:account_update) << [:name, :admin]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource param_method: :comment_params
  load_and_authorize_resource :duel

  def index

  end


  def new

  end

  def create
    @comment = @duel.comments.new(comment_params)
    if @comment.save
      current_user.comments.push(@comment)
      respond_to do |format|
        format.html {redirect_to root_path}
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js { render 'fail'}
      end
    end
  end

  def edit

  end

  def destroy

  end


  private def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/duels_controller.rb
class DuelsController < ApplicationController
  load_and_authorize_resource param_method: :duels_params
  def new
  end

  def show
  end

  def destroy
    if @duel.destroy
      redirect_to root_path, notice: "Successfully deleted duel"
    else
      render :root_path, alert: "error in deleting duel"
    end
  end

  def index
    @comment = Comment.new(body: '')
    @duel = Duel.new
  end

  def create
    if @duel.save
      redirect_to root_path, notice: "Successfully added duel"
    else
      render :new
    end
  end

  def update
    if @duel.update(duels_params)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js { render 'percent-bar' }
        flash[:notice] = "awesome sauce"
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js { render 'fail'}
        flash[:alert] = 'yar their bee some issues'
      end
    end
  end

  private def duels_params
    params.require(:duel).permit(:name, :character_one_name, :character_two_name, :character_one_body,
     :character_two_body, :character_one_avatar, :character_two_avatar, :character_one_votes, :character_two_votes)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= render 'layouts/errors', object: @comment %>

<%= bootstrap_form_for [duel, @comment ], remote: true do |f| %>
  <%= f.text_field :body %>
  <%= f.submit "Smash!", data: {disable_with: 'Smashing...'}, class: "btn btn-block btn-primary"%>
<% end %>

app/views/comments/create.js.erb
$('#comment-holder<%= @duel.id %>').prepend('<div class="row comments">\
                                             <span class="comment"><%= @comment.body %></span>\
                                             <span class="comment-time"><%= time_ago_in_words(@comment.created_at) %> ago</span>\
                                             </div>');

app/views/comments/fail.js.erb
$('.container').prepend('<%= j render "layouts/errors", object: @comment %>');

app/views/comments/new.html.erb
<%= render 'form', duel: @duel %>

app/views/duels/_form.html.erb
<%= render 'layouts/errors', object: @duel %>

<%= bootstrap_form_for @duel do |f| %>
  <%= f.text_field :name %>
  <div class="row">
    <div class="col-md-6">
      <%= f.text_field :character_one_name %>
      <%= f.file_field :character_one_avatar %>
      <%= f.text_field :character_one_body %>
    </div>
    <div class="col-md-6">
      <%= f.text_field :character_two_name %>
      <%= f.file_field :character_two_avatar %>
      <%= f.text_field :character_two_body %>
    </div>
    <%= f.submit "Smash!", data: {disable_with: 'Smashing...'}, class: "btn btn-block btn-primary"%>
  </div>
<% end %>
<br>

app/views/duels/create.js.erb
$('#new_duel').remove();
$('#new-duel').show();

app/views/duels/index.html.erb
<%= link_to 'Add New Smash', new_duel_path, id:'new-duel', remote: true, class: "btn btn-block btn-primary"%>

<% if @duels.any? %>
  <% @duels.each do |duel| %>
    <div class="row panel duel-content">
      <div class="col-md-6 voting" id="duel-box<%= duel.id %>">
        <h3 class="text-center"><%= duel.name %></h3>
        <div class="row">
          <div id="duel<%= duel.id %>_1" class="photo">
            <%= bootstrap_form_for duel, remote: true do |f| %>
              <%= f.hidden_field :character_one_votes, value: duel.character_one_votes += 1 %>
              <%= duel.character_one_name %> - <%= duel.character_one_votes %><br>
              <%= image_tag duel.character_one_image(:medium) %><br>
              <%= duel.character_one_body %>
            <% end %>
          </div>
          <div id="duel<%= duel.id %>_2" class="photo right">
            <%= bootstrap_form_for duel, remote: true do |f| %>
              <%= f.hidden_field :character_two_votes, value: duel.character_two_votes += 1 %>
              <%= duel.character_two_name %> - <%= duel.character_two_votes %><br>
              <%= image_tag duel.character_two_image(:medium) %><br>
              <%= duel.character_two_body %>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="progress" id='progress-bar<%= duel.id %>'>
            <div class="progress-bar progress-bar-success" role="progressbar" style="width:<%= duel.vote_percent_one %>%">
              <%= duel.character_one_name %> - <%= duel.vote_percent_one.round(1) %>%
            </div>
            <div class="progress-bar progress-bar-warning" role="progressbar" style="width:<%= duel.vote_percent_two %>%">
              <%= duel.character_two_name %> - <%= duel.vote_percent_two.round(1) %>%
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-5 border">
          <%= render 'comments/form', duel: duel %>
          <div class="comment-holder" id="comment-holder<%= duel.id %>">
          <% duel.comments.take(3).each do |comment| %>
            <div class="row comments">
              <span class="comment"><%= comment.body %></span><span class="comment-time"><%= time_ago_in_words(comment.created_at) %> ago</span>
            </div>
          <% end %>
          </div>
      </div>
    </div>
    <% if current_user.admin? %>
      <div class="row delete-button">
        <%= link_to "Delete", duel_path(duel), data: {disable_with: 'Smashing...', method: :delete}, class: "btn btn-block btn-primary"%>
      </div>
    <% end %>
    <hr>
  <% end %>
<% else %>
<h3 class="text-center">

 Nothing is currently being smashed, create smash <%= link_to 'here!', new_duel_path %>
</h3>
<% end %>

app/views/duels/new.html.erb
<%= render "form" %>

app/views/duels/new.js.erb
$('#new-duel').hide().after('<%= j render("form") %>');

app/views/duels/percent-bar.js.erb
$('#duel-box<%= @duel.id %>').html('<h3 class="text-center"><%= @duel.name %></h3>\
<div class="row">\
  <div id="@duel<%= @duel.id %>_1" class="photo">\
    <%= bootstrap_form_for @duel, remote: true do |f| %>\
      <%= f.hidden_field :character_one_votes, value: @duel.character_one_votes += 1 %>\
      <%= @duel.character_one_name %> - <%= @duel.character_one_votes %><br>\
      <%= image_tag @duel.character_one_image(:medium) %><br>\
      <%= @duel.character_one_body %>\
    <% end %>\
  </div>\
  <div id="@duel<%= @duel.id %>_2" class="photo right">\
    <%= bootstrap_form_for @duel, remote: true do |f| %>\
      <%= f.hidden_field :character_two_votes, value: @duel.character_two_votes += 1 %>\
      <%= @duel.character_two_name %> - <%= @duel.character_two_votes %><br>\
      <%= image_tag @duel.character_two_image(:medium) %><br>\
      <%= @duel.character_two_body %>\
    <% end %>\
  </div>\
</div>\
<div class="row">\
  <div class="progress" id="progress-bar<%= @duel.id %>">\
    <div class="progress-bar progress-bar-success" role="progressbar" style="width:<%= @duel.vote_percent_one %>%">\
      <%= @duel.character_one_name %> - <%= @duel.vote_percent_one.round(1) %>%\
    </div>\
    <div class="progress-bar progress-bar-warning" role="progressbar" style="width:<%= @duel.vote_percent_two %>%">\
      <%= @duel.character_two_name %> - <%= @duel.vote_percent_two.round(1) %>%\
    </div>\
  </div>\
</div>');

app/views/duels/show.html.erb
<div class='col-md-3'>
  <%= image_tag @duel.character_one_image(:medium), class: 'img-responsive' %>
</div>

<div class='col-md-3'>
  <%= image_tag @duel.character_two_image(:medium), class: 'img-responsive' %>
</div>
<div class="col-md-6">
  <% if @duel.comments.any? %>
    <% @duel.comments.each do |comment| %>
      <div class="row comments">
        <span class="comment"><%= comment.body %></span><span class="comment-time"><%= time_ago_in_words(comment.created_at) %> ago</span>
      </div>

    <% end %>

  <% end %>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><strong>SmashOff!</strong></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <% if current_user.admin? %>
        <li><a>
        Admin
        </a> </li>
        <% end %>
        <li><%= link_to "Add Smash", new_duel_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <%= current_user.email %><span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <li><%= link_to "Profile", user_path(current_user) %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <span class="badge badge-warning"><%=  %></span>
          </a>
        </li>
        <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smashing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<% if flash[:notice] %>
  <div class="alert alert-dismisable alert-success text-center" role="alert" style="margin-bottom: 0px;">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-dismisable alert-danger text-center" role="alert" style="margin-bottom: 0px;">
    <%= flash[:alert] %>
  </div>
<% end %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/users/show.html.erb
<h1 class="page-header text-center">
  Profile for <strong><%= @user.name %></strong>
</h1>
<% if current_user == @user %>
<%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-block btn-default" %>
<% end %>